name: innim_lint
description: The Dart analyzer settings and linter rules used at Innim for Dart and Flutter projects. Stricter than pedantic.
version: 0.1.2+1
homepage: https://github.com/innim/
repository: https://github.com/Innim/dart-lint
issue_tracker: https://github.com/Innim/dart-lint/issues

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  pedantic: ^1.9.2
